"""
SAGE Payload Library — Pre-computed adversarial payload storage.

Stores payloads generated by offline MCTS with H-Neuron and LAT telemetry
scores. Loaded at battle-time by LibraryLoader to replace live generation
with 1 API call instead of 4.

Storage format: JSON, one file per (game_type, model_id) pair.
Location: ./payload_libraries/<game_type>_<model_id>.json

Scoring formula (corrected for defender simulacrum architecture):
    composite = 0.4 * h_score + 0.6 * lat_score
    h_score: H-Neuron score on DEFENDER (high = defender being coerced) — want HIGH
    lat_score: LAT probe coercion probability on DEFENDER (0-1) — want HIGH
    composite: higher = better payload (both signals measure defender brainwashing)
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Iterator


@dataclass
class PayloadEntry:
    """A single pre-computed adversarial payload with telemetry scores.

    Fields
    ------
    payload : str
        The attack text to deliver to the defender.
    game_type : str
        Scenario type this payload targets (e.g. 'safety_bypass',
        'evidence_manipulation', 'safety_jailbreak', 'information_extraction').
    strategy : str
        UCB1 strategy that generated this payload (e.g. 'authority_persona').
    mutation : str
        Mutation applied on top of the base strategy (e.g. 'encoding_base64').
    h_score : float
        H-Neuron score measured on the DEFENDER [0, 1]. High = defender showing
        over-compliance (being coerced by the attack). Want HIGH.
    lat_score : float
        LAT probe coercion probability on DEFENDER [0, 1]. High = defender's
        honesty representation is degraded (attack is working). Want HIGH.
    composite_score : float
        Primary ranking key: 0.4*h_score + 0.6*lat_score.
    oracle_model : str
        Model ID used to generate this payload (e.g. 'TinyLlama-1.1B',
        'meta-llama/Llama-3.2-1B-Instruct', 'openai/gpt-oss-20b').
    episode : int
        Offline MCTS episode number that produced this payload.
    timestamp : float
        Unix timestamp of generation.
    used_in_battle : bool
        True if this payload has already been delivered in a live round.
        LibraryLoader sets this to avoid replaying failed payloads.
    battle_result : float | None
        Actual reward received in the live round (set post-battle).
        None = not yet used live.
    """
    payload: str
    game_type: str
    strategy: str
    mutation: str
    h_score: float
    lat_score: float
    composite_score: float
    oracle_model: str
    episode: int = 0
    timestamp: float = field(default_factory=time.time)
    used_in_battle: bool = False
    battle_result: float | None = None

    @classmethod
    def from_scores(
        cls,
        payload: str,
        game_type: str,
        strategy: str,
        mutation: str,
        h_score: float,
        lat_score: float,
        oracle_model: str,
        episode: int = 0,
    ) -> "PayloadEntry":
        """Construct with composite_score computed automatically."""
        composite = 0.4 * h_score + 0.6 * lat_score
        return cls(
            payload=payload,
            game_type=game_type,
            strategy=strategy,
            mutation=mutation,
            h_score=h_score,
            lat_score=lat_score,
            composite_score=composite,
            oracle_model=oracle_model,
            episode=episode,
        )

    def to_dict(self) -> dict:
        return asdict(self)

    @classmethod
    def from_dict(cls, d: dict) -> "PayloadEntry":
        return cls(**{k: v for k, v in d.items() if k in cls.__dataclass_fields__})


class PayloadLibrary:
    """Collection of pre-computed payloads with filtering and persistence.

    Usage
    -----
    # Build during offline MCTS:
    lib = PayloadLibrary(oracle_model="TinyLlama-1.1B")
    lib.add(PayloadEntry.from_scores(...))
    lib.save("./payload_libraries/safety_bypass_tinyllama.json")

    # Load at battle-time:
    lib = PayloadLibrary.load("./payload_libraries/safety_bypass_tinyllama.json")
    best = lib.top_k(game_type="safety_bypass", k=5)
    """

    def __init__(self, oracle_model: str = "unknown") -> None:
        self.oracle_model = oracle_model
        self._entries: list[PayloadEntry] = []

    def __len__(self) -> int:
        return len(self._entries)

    def __iter__(self) -> Iterator[PayloadEntry]:
        return iter(self._entries)

    # ------------------------------------------------------------------
    # Adding entries
    # ------------------------------------------------------------------

    def add(self, entry: PayloadEntry) -> None:
        """Add a payload entry."""
        self._entries.append(entry)

    def add_batch(self, entries: list[PayloadEntry]) -> None:
        """Add multiple entries at once."""
        self._entries.extend(entries)

    # ------------------------------------------------------------------
    # Querying
    # ------------------------------------------------------------------

    def top_k(
        self,
        game_type: str,
        k: int = 5,
        exclude_used: bool = True,
        min_composite: float = 0.0,
        max_h_score: float = 1.0,
    ) -> list[PayloadEntry]:
        """Return top-k payloads for a game type, ranked by composite_score.

        Args:
            game_type: Scenario type to filter by.
            k: Number of payloads to return.
            exclude_used: If True, skip payloads already delivered in battle.
            min_composite: Minimum composite score threshold (default: no filter).
            max_h_score: Kept for API compatibility; default 1.0 = no filter.
                         In the defender-simulacrum architecture, high h_score
                         is desirable (coercion signal), so leave at default.

        Returns:
            Up to k PayloadEntry objects, sorted best-first.
        """
        candidates = [
            e for e in self._entries
            if e.game_type == game_type
            and (not exclude_used or not e.used_in_battle)
            and e.composite_score >= min_composite
            and e.h_score <= max_h_score
        ]
        candidates.sort(key=lambda e: e.composite_score, reverse=True)
        return candidates[:k]

    def by_strategy(self, game_type: str, strategy: str, k: int = 3) -> list[PayloadEntry]:
        """Return top-k payloads for a specific strategy within a game type."""
        candidates = [
            e for e in self._entries
            if e.game_type == game_type and e.strategy == strategy
        ]
        candidates.sort(key=lambda e: e.composite_score, reverse=True)
        return candidates[:k]

    def game_types(self) -> list[str]:
        """Return sorted list of unique game types in this library."""
        return sorted({e.game_type for e in self._entries})

    def stats(self) -> dict:
        """Summary statistics for logging / debugging."""
        if not self._entries:
            return {"total": 0}

        by_type: dict[str, list[float]] = {}
        for e in self._entries:
            by_type.setdefault(e.game_type, []).append(e.composite_score)

        return {
            "total": len(self._entries),
            "oracle_model": self.oracle_model,
            "game_types": {
                gt: {
                    "count": len(scores),
                    "mean_composite": sum(scores) / len(scores),
                    "best_composite": max(scores),
                }
                for gt, scores in by_type.items()
            },
            "used_in_battle": sum(1 for e in self._entries if e.used_in_battle),
        }

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def save(self, path: str) -> None:
        """Serialize library to JSON.

        Args:
            path: File path. Parent directories are created if needed.
        """
        p = Path(path)
        p.parent.mkdir(parents=True, exist_ok=True)
        data = {
            "oracle_model": self.oracle_model,
            "saved_at": time.time(),
            "count": len(self._entries),
            "entries": [e.to_dict() for e in self._entries],
        }
        p.write_text(json.dumps(data, indent=2))

    @classmethod
    def load(cls, path: str) -> "PayloadLibrary":
        """Load library from JSON file.

        Args:
            path: File path written by save().

        Raises:
            FileNotFoundError: If the file does not exist.
        """
        p = Path(path)
        if not p.exists():
            raise FileNotFoundError(
                f"Payload library not found: {p}\n"
                "Generate one with: uv run python scripts/run_offline_mcts.py"
            )
        data = json.loads(p.read_text())
        lib = cls(oracle_model=data.get("oracle_model", "unknown"))
        lib._entries = [
            PayloadEntry.from_dict(e) for e in data.get("entries", [])
        ]
        return lib

    @classmethod
    def load_or_empty(cls, path: str, oracle_model: str = "unknown") -> "PayloadLibrary":
        """Load from path if it exists, otherwise return an empty library."""
        try:
            return cls.load(path)
        except FileNotFoundError:
            return cls(oracle_model=oracle_model)

    def merge(self, other: "PayloadLibrary") -> "PayloadLibrary":
        """Return a new library combining entries from both.

        Useful for merging Phase A (TinyLlama) and Phase B (gpt-oss-20b) libraries.
        """
        merged = PayloadLibrary(oracle_model=f"{self.oracle_model}+{other.oracle_model}")
        merged._entries = self._entries + other._entries
        return merged
